linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - copyloopvar       # keep around for now
    - cyclop            # covered by gocyclo
    - depguard          # lots of exceptions for this specific module
    - execinquery       # deprecated in golangci v1.58
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomnd             # deprecated in golangci v1.58 in favor of mnd
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - mnd               # some unnamed constants are okay
    - nlreturn          # generous whitespace violates house style
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
    - exhaustruct       # exhaustive struct checks are noisy
issues:
  exclude-dirs-use-default: false
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
  exclude-rules:
    # We don't want to list out all the fields for appcmd.Cmd or flags.
    - linters: [exhaustruct]
      path: cmd/license-header/main.go
    # The current nested block is actually the simplest way to do this
    # without refactoring.
    - linters: [nestif]
      path: cmd/license-header/main.go
